### ISSUE TITLE
How I can initilize the plugin ?

### ISSUE THREAD

**Issue by ARoSistemas** [liyufengrex/android_usb_printer#1]
How I can initilize the plugin ?

```
 try {
      platformVersion = await _androidUsbPrinterPlugin
              .queryLocalUsbDevice()
              .then(
                  (value) => value.map((e) => e.toMap()).toList().toString()) ??
          'Unknown platform version';
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    
   //  The error ::  lateinit property usbManager has not been initialized 
}

```

Launching lib/main.dart on SM A225M in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/MethodChannel#android_usb_printer_method_channel(31512): Failed to handle method call
E/MethodChannel#android_usb_printer_method_channel(31512): kotlin.UninitializedPropertyAccessException: lateinit property usbManager has not been initialized
E/MethodChannel#android_usb_printer_method_channel(31512): 	at com.rex.android_usb_printer.tools.UsbDeviceHelper.queryPrinterDevices(UsbDeviceHelper.kt:82)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at com.rex.android_usb_printer.tools.UsbDeviceHelper.queryLocalPrinterMap(UsbDeviceHelper.kt:56)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at com.rex.android_usb_printer.AndroidUsbPrinterPlugin.onMethodCall(AndroidUsbPrinterPlugin.kt:83)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#android_usb_printer_method_channel(31512): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/ion     (31512): ioctl c0044901 failed with code -1: Invalid argument
D/hw-ProcessState(31512): Binder ioctl to enable oneway spam detection failed: Invalid argument
I/BLASTBufferQueue(31512): [SurfaceView[mx.com.enginecore.printer_usb_demo/mx.com.enginecore.printer_usb_demo.MainActivity]@0#1](f:0,a:0) onFrameAvailable the first frame is available
D/BLASTBufferQueue(31512): [SurfaceView[mx.com.enginecore.printer_usb_demo/mx.com.enginecore.printer_usb_demo.MainActivity]@0#1](f:0,a:1) acquireNextBufferLocked size=720x1510 mFrameNumber=1 applyTransaction=true mTimestamp=512102526132676(auto) mPendingTransactions.size=0 graphicBufferId=135343009431552 transform=0
D/SurfaceView@eefd165(31512):  setAlpha: mUseAlpha = false alpha=1.0
D/SurfaceView@eefd165(31512):  updateSurfaceAlpha: setUseAlpha() is not called, ignored.
I/ViewRootImpl@bf5c919[MainActivity](31512): Setup new sync id=0
I/ViewRootImpl@bf5c919[MainActivity](31512): Setting syncFrameCallback
I/ViewRootImpl@bf5c919[MainActivity](31512): registerCallbacksForSync syncBuffer=false
D/SurfaceView@eefd165(31512): updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 720, 1510] surfaceSize = 720x1510
I/SurfaceView@eefd165(31512): uSP: rtp = Rect(0, 0 - 720, 1510) rtsw = 720 rtsh = 1510
I/SurfaceView@eefd165(31512): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@eefd165(31512): aOrMT: ViewRootImpl@bf5c919[MainActivity] t = android.view.SurfaceControl$Transaction@16fe997 fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:373
I/ViewRootImpl@bf5c919[MainActivity](31512): mWNT: t=0xb4000071043afb00 mBlastBufferQueue=0xb40000718ac20100 fn= 1 caller= android.view.SurfaceView.applyOrMergeTransaction:1455 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537
I/ViewRootImpl@bf5c919[MainActivity](31512): mWNT: t=0xb4000071043af900 mBlastBufferQueue=0xb40000718ac20100 fn= 1 caller= android.view.ViewRootImpl.lambda$applyTransactionOnDraw$11$android-view-ViewRootImpl:12865 android.view.ViewRootImpl$$ExternalSyntheticLambda1.onFrameDraw:4 android.graphics.HardwareRenderer$FrameDrawingCallback.onFrameDraw:924
I/ViewRootImpl@bf5c919[MainActivity](31512): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@bf5c919[MainActivity](31512): Setting up sync and frameCommitCallback
I/BLASTBufferQueue(31512): [ViewRootImpl@bf5c919[MainActivity]#0](f:0,a:0) onFrameAvailable the first frame is available
D/BLASTBufferQueue(31512): [ViewRootImpl@bf5c919[MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=720x1600 mFrameNumber=1 applyTransaction=true mTimestamp=512102569816599(auto) mPendingTransactions.size=0 graphicBufferId=135343009431553 transform=0
I/ViewRootImpl@bf5c919[MainActivity](31512): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer(31512): CFMS:: SetUp Pid : 31512    Tid : 31535
W/Parcel  (31512): Expecting binder but got null!
I/ViewRootImpl@bf5c919[MainActivity](31512): onSyncComplete
I/ViewRootImpl@bf5c919[MainActivity](31512): setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503
I/ViewRootImpl@bf5c919[MainActivity](31512): reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb400007187217a00
I/ViewRootImpl@bf5c919[MainActivity](31512): MSG_WINDOW_FOCUS_CHANGED 1 0
I/ViewRootImpl@bf5c919[MainActivity](31512): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb40000712cdc1000}
D/InputMethodManager(31512): startInputInner - Id : 0
I/InputMethodManager(31512): startInputInner - mService.startInputOrWindowGainedFocus
D/InputMethodManager(31512): startInputInner - Id : 0
D/InsetsController(31512): onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 720, 1600), mDisplayCutout=DisplayCutout{insets=Rect(0, 58 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(298, 0 - 422, 58), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=720 displayHeight=1600 physicalDisplayWidth=720 physicalDisplayHeight=1600 density={1.875} cutoutSpec={M62.05,0l-2.7,0l-2.7,0l-1.4,0.1L53.95,0.2l-1.3,0.2l-1.3,0.2L49.95,0.9l-1.3,0.4l-1.3,0.5l-1.2,0.6L44.95,3 l-1.1,0.7l-1,0.8l-1,0.9l-0.9,1l-0.8,1l-0.7,1.1l-0.7,1.2l-0.6,1.2l-0.5,1.3l-0.4,1.3l-0.4,1.3l-0.5,2.3l-0.4,2.3l-0.4,2.3L34.95,23.9 l-0.6,2.3l-0.7,2.2l-0.4,1.1L32.95,30.6l-0.5,1.1L31.95,32.7c-3.5,7.2-9.3,13.1-16.6,16.6c-17.7,8.5-38.9,1.1-47.4-16.6l-0.5-1.1 l-0.5-1.1l-0.4-1.1l-0.4-1.1l-0.7-2.2l-0.6-2.3l-0.5-2.3l-0.4-2.3l-0.4-2.3l-0.5-2.3l-0.4-1.3l-0.4-1.3L-38.15,11l-0.6-1.2l-0.7-1.2 L-40.05,7.5l-0.8-1l-0.9-1l-1-0.9l-1-0.8L-44.95,3l-1.2-0.6l-1.2-0.6l-1.3-0.5l-1.3-0.4l-1.3-0.3L-52.55,0.4L-53.95,0.2L-55.25,0.1L-56.65,0L-59.35,0 L-62.05,0Z} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=60, center=Point(60, 60)}, RoundedCorner{position=TopRight, radius=60, center=Point(660, 60)}, RoundedCorner{position=BottomRight, radius=60, center=Point(660, 1540)}, RoundedCorner{position=BottomLeft, radius=60, center=Point(60, 1540)}]}  mRoundedCornerFrame=Rect(0, 0 - 720, 1600), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(637, 0 - 720, 58) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][720,58], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,1510][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[720,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][720,81], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,1510][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][720,58], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][720,58], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,1510][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisibleFrame=[0,1510][720,1600], mVisible=false, mInsetsRoundedCornerFrame=false} } host=mx.com.enginecore.printer_usb_demo/mx.com.enginecore.printer_usb_demo.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6740
Application finished.
Exited

**Comment by jiangchengze** [comment]
I encountered the same problem

**Comment by jiangchengze** [comment]
targetSdkVersion 30 is normal. If it is higher than 30, an error will be reported. I hope it can be fixed.
